# Generated by Django 5.0.2 on 2025-05-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreathingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "pattern",
                    models.JSONField(
                        help_text="Breath pattern configuration (e.g., [inhale, hold, exhale, hold])"
                    ),
                ),
                (
                    "timer_seconds",
                    models.PositiveIntegerField(
                        default=60, help_text="Default session duration in seconds"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True, help_text="Image, video, or animation URL"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breathing_exercises",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeditationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("audio_url", models.URLField(blank=True, help_text="Audio file URL")),
                (
                    "script",
                    models.TextField(blank=True, help_text="Guided meditation script"),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=600, help_text="Session duration in seconds"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(blank=True, help_text="Image or video URL"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meditation_sessions",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CombinedRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "transition_notes",
                    models.TextField(
                        blank=True,
                        help_text="Instructions for transitions between exercise types",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "breathing_exercises",
                    models.ManyToManyField(
                        blank=True,
                        related_name="combined_routines",
                        to="routines.breathingexercise",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combined_routines",
                        to="users.userprofile",
                    ),
                ),
                (
                    "routines",
                    models.ManyToManyField(
                        blank=True,
                        related_name="combined_routines",
                        to="routines.routine",
                    ),
                ),
                (
                    "meditation_sessions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="combined_routines",
                        to="routines.meditationsession",
                    ),
                ),
            ],
        ),
    ]
