# Generated by Django 5.0.2 on 2025-05-21 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0002_breathingexercise_meditationsession_combinedroutine"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("consistency", "Consistency"),
                            ("mastery", "Mastery"),
                            ("milestone", "Milestone"),
                            ("special", "Special"),
                        ],
                        max_length=16,
                    ),
                ),
                ("icon_url", models.URLField(blank=True)),
                (
                    "criteria",
                    models.JSONField(
                        help_text="Achievement criteria (e.g., {'exercise_count': 10, 'days_streak': 7})"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="breathingexercise",
            name="media_url",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="media_url",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="audio_url",
        ),
        migrations.RemoveField(
            model_name="meditationsession",
            name="media_url",
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("animation", "Animation"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL to the media file in Supabase Storage"
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, help_text="URL to thumbnail for videos"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration for video/audio in seconds",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="breathingexercise",
            name="media_assets",
            field=models.ManyToManyField(
                blank=True, related_name="breathing_exercises", to="routines.mediaasset"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="media_assets",
            field=models.ManyToManyField(
                blank=True, related_name="exercises", to="routines.mediaasset"
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="audio_assets",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"asset_type": "audio"},
                related_name="meditation_audio_sessions",
                to="routines.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="media_assets",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"asset_type__in": ["image", "video"]},
                related_name="meditation_visual_sessions",
                to="routines.mediaasset",
            ),
        ),
        migrations.CreateModel(
            name="ClientAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "progress_data",
                    models.JSONField(
                        default=dict,
                        help_text="Data about how the achievement was earned",
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_achievements",
                        to="routines.achievement",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="ExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        help_text="Time spent on exercise in seconds"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "difficulty_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "breathing_exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_tracking",
                        to="routines.breathingexercise",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_progress",
                        to="users.userprofile",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_tracking",
                        to="routines.exercise",
                    ),
                ),
                (
                    "meditation_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_tracking",
                        to="routines.meditationsession",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("client", "breathing_exercise", "completed_at"),
                    ("client", "exercise", "completed_at"),
                    ("client", "meditation_session", "completed_at"),
                },
            },
        ),
    ]
